variables:
  ENV_TAG: au_dev_0.0.1
  AZURE_LOCATION: australiasoutheast
  AZURE_ACR_NAME: $(global_variable)_acr

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: PowerShell@2
    inputs:
      filePath: 'deploy.ps1'
      arguments: '
        -Bootstrap
      '
      failOnStderr: true
      pwsh: true