variables:
  ENV_TAG: au_dev_0.0.1
  AZURE_LOCATION: australiasoutheast
  AZURE_RG_NAME: $(ENV_TAG)_rg
  AZURE_ACR_NAME: $(ENV_TAG)_acr

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: PowerShell@2
    inputs:
      filePath: 'deploy.ps1'
      arguments: '
        -Bootstrap
        -Task Deploy
      '
      failOnStderr: true
      pwsh: true
    env:
      AZURE_SP_PASSWORD: $(azure.sp.password)